### ISSUE TITLE
Can't run tmuxinator

### ISSUE THREAD

**Issue by pedrocaseiro** [tmuxinator/tmuxinator#503]
I'm getting the following error when I try to run any tmuxinator command, like tmuxinator ls or mux ls.
Any idea?

```
/Users/caseiro/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
Did you mean?  Bundler::Plugin::API::Source
               Bundler::Source
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:143:in `map'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:76:in `contains_requirable_file?'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:949:in `block in find_in_unresolved'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:949:in `each'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:949:in `find_all'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:949:in `find_in_unresolved'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:74:in `require'
	from /Users/caseiro/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/caseiro/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:143:in `map'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1370:in `add_self_to_load_path'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1283:in `activate'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1300:in `each'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1282:in `activate'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /Users/caseiro/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /Users/caseiro/.rvm/gems/ruby-2.3.0/bin/tmuxinator:22:in `<main>'
	from /Users/caseiro/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/caseiro/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

It was working yesterday, but I think it broke after a mac udpate

**Comment by ethagnawl** [comment]
Hi @pedrocaseiro,

Have you seen [this](https://github.com/bundler/bundler/pull/4981) Bundler issue? It sounds like you're running into this problem, which should be solved by upgrading to >= 1.13.4.

**Comment by pedrocaseiro** [comment]
@ethagnawl My bundler version is already >= 1.13.4, it's 1.14.3 :/

**Comment by andrewdang17** [comment]
I have this same issue, did you ever find a way to fix it @pedrocaseiro ?

**Comment by pedrocaseiro** [comment]
@andrewdang17 Sometimes I can run it, it depends on the folder I'm currently at.

**Comment by uhrohraggy** [comment]
+1 am running bundle 1.14.3 and getting this.

**Comment by pachonk** [comment]
I have this issue currently. It's weird and it is seeming to be related to RVM directly. I get this error when using tmuxinator:
```
Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/rvm/rvm/issues/3212
```

**Comment by adamstrickland** [comment]
@pachonk as you noted, this appears to be an issue with the local shell setup and rvm, not tmuxinator directly.  The thread referenced in the RVM error is long and not very focused, but hits on several possible causes; among them: using `oh-my-zsh` or other `$PATH`-clobbering shell setup, using a non-login shell, not `source`ing `$HOME/.rvm/scripts/rvm`, insuring an up-to-date version of rvm...  Can you confirm that RVM works w/out a problem in a "normal" shell session?

**Comment by pachonk** [comment]
@adamstrickland I always said the day I had issues related to RVM, I'd switch. I switched to asdf which is way more amazing and supports node too, and everything works.
It's directly related to RVM or ohmyzsh. I had both of those when having tmuxinator.
Side note, asdf is great
