### ISSUE TITLE
Error on pre_window when parsing arrays

### ISSUE THREAD

**Issue by edman** [tmuxinator/tmuxinator#539]
I'm getting an error when trying to setup multiple commands on pre_window.

Here's a sample config file that triggers the error.

```
name: test
pre_window:
  - export DIR=~/workspace
windows:
  - main:
```

Here's the output.
```
$ tmuxinator version
tmuxinator 0.9.0
$ tmuxinator start test
/var/lib/gems/1.9.1/gems/tmuxinator-0.9.0/lib/tmuxinator/window.rb:87:in `tmux_pre_window_command': undefined method `shellescape' for ["export DIR=~/workspace"]:Array (NoMethodError)
        from (erubis:42:in `block in render'
        from (erubis:34:in `each'
        from (erubis:34:in `render'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
        from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
        from /var/lib/gems/1.9.1/gems/tmuxinator-0.9.0/lib/tmuxinator/project.rb:90:in `render'
        from /var/lib/gems/1.9.1/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:126:in `render_project'
        from /var/lib/gems/1.9.1/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:150:in `start'
        from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /var/lib/gems/1.9.1/gems/tmuxinator-0.9.0/bin/tmuxinator:15:in `<top (required)>'
        from /usr/local/bin/tmuxinator:23:in `load'
        from /usr/local/bin/tmuxinator:23:in `<main>'
```

**Comment by adamstrickland** [comment]
To the best of my knowledge, `tmuxinator` doesn't support array values for hooks (e.g. `pre_window`).  I recommend using a string value instead, e.g.

```yaml
pre_window: export DIR=~/workspace
```

**Comment by edman** [comment]
It seems array parsing on pre_window was introduced on #482.

I'm aware strings work, that was a config to reproduce the error.

**Comment by adamstrickland** [comment]
https://github.com/tmuxinator/tmuxinator/pull/482 is in `master` but has not yet been released.

I can confirm that `pre_window` values as Arrays fail in `tmuxinator 0.9.0` as reported, but this is functionality not supported by that version.

The `master` branch `tmuxinator` binary _does_ support this functionality.
