### ISSUE TITLE
Deleting mux project fails

### ISSUE THREAD

**Issue by brandoncordell** [tmuxinator/tmuxinator#560]
MacOS Sierra 10.12.6
Ruby 2.4.2p198
Tmuxinator 0.9.0

```
$ mux delete test_project
Are you sure you want to delete test_project?(y/n) y
/usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:220:in `block in delete': uninitialized constant Tmuxinator::Cli::FileUtils (NameError)
Did you mean?  FileTest
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:215:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:215:in `delete'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/bin/tmuxinator:15:in `<top (required)>'
	from /usr/local/bin/tmuxinator:23:in `load'
	from /usr/local/bin/tmuxinator:23:in `<main>'
```

**Comment by nwshane** [comment]
@brandoncordell Did you figure out a fix for this? I'm getting the same error.

**Comment by brandoncordell** [comment]
@nwshane I just deleted the project file itself (`~/.tmuxinator/<project_name>` IIRC). I don't remember if the delete command did anything else besides that, but that will work.

**Comment by nwshane** [comment]
@brandoncordell That worked - thanks!

**Comment by ethagnawl** [comment]
Closing this for now. Please re-open if anyone is still seeing this behavior.
