### ISSUE TITLE
Can't find method `generate_project_file`

### ISSUE THREAD

**Issue by chris-fa** [tmuxinator/tmuxinator#561]
This might be a dumb issue. I had tmuxinator working a couple of days ago. Now I attempted to create a second project by running `new` and I got this error:

```bash
$ tmuxinator new test
(erubis:4:in `generate_project_file': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:93:in `generate_project_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:86:in `find_project_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/lib/tmuxinator/cli.rb:72:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.9.0/bin/tmuxinator:15:in `<top (required)>'
	from /usr/local/bin/tmuxinator:23:in `load'
	from /usr/local/bin/tmuxinator:23:in `<main>'
```
### Versions

```bash
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

$ gem -v
2.6.13
```

#### Update
When I run `tmuxinator open default` or `tmuxinator default` (my default project) it works, specifically `new` is the command that doesn't

**Comment by rglassett** [comment]
@chris-fa can you post the contents of your `default.yml` and `sample.yml` if they exist?

**Comment by ethagnawl** [comment]
Closing this for now. If anyone is still having this issue, please re-open.
