### ISSUE TITLE
Tmux version 3.4 should be supported but isn't

### ISSUE THREAD

**Issue by robplan** [tmuxinator/tmuxinator#899]
**Describe the bug**
Tmux v3.4 should be supported, but Tmuxinator raises an error and shows the "WARNING: You are running tmuxinator with an unsupported version of tmux." message.

**To Reproduce**
Run Tmuxinator using v3.4 of Tmux

**Expected behavior**
Tmuxinator should run without showing the rror

**Environment**
 - tmuxinator Version: running off of master commit 9918ed6 
- tmux Version: 3.4
 - Ruby Version: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin23]
 - OS: this happens on MacOS, but pretty sure it happens everywhere

**Comment by brandondrew** [comment]
I get the same behavior:

```zsh
brandon@Air portal % which tmux
/opt/homebrew/bin/tmux
brandon@Air portal % tmux -V
tmux 3.4
brandon@Air portal % tmuxinator --version
    WARNING: You are running tmuxinator with an unsupported version of tmux.
    Please consider using a supported version:
    (3.4, 3.3a, 3.3, 3.2a, 3.2, 3.1c, 3.1b, 3.1a, 3.1, 3.0a, 3.0, 2.9a, 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9, 1.8, 1.7, 1.6, 1.5)

Press ENTER to continue.^C/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/tmuxinator-3.1.1/lib/tmuxinator/cli.rb:223:in `getc': Interrupt
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/tmuxinator-3.1.1/lib/tmuxinator/cli.rb:223:in `show_continuation_prompt'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/tmuxinator-3.1.1/lib/tmuxinator/cli.rb:217:in `show_version_warning'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/tmuxinator-3.1.1/lib/tmuxinator/cli.rb:259:in `start'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/tmuxinator-3.1.1/lib/tmuxinator/cli.rb:437:in `bootstrap'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/tmuxinator-3.1.1/bin/tmuxinator:7:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.3.0/bin/tmuxinator:25:in `load'
	from /Users/brandon/.rbenv/versions/3.3.0/bin/tmuxinator:25:in `<main>'

brandon@Air portal % which tmuxinator          
/Users/brandon/.rbenv/shims/tmuxinator
brandon@Air portal % rbenv local
3.3.0
```

**Comment by farzadmf** [comment]
Same here; happening with `tmuxinator version -> 3.1.1` and `tmux -V -> 3.4`

**Comment by robplan** [comment]
fixed by https://github.com/tmuxinator/tmuxinator/pull/898
