### ISSUE TITLE
tmuxinator don't execute

### ISSUE THREAD

**Issue by SyscallBrain** [tmuxinator/tmuxinator#938]
```ruby
<internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- erb (LoadError)
Did you mean?  drb
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/actions/file_manipulation.rb:1:in `<top (required)>'
        from /usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/actions.rb:5:in `require_relative'
        from /usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/actions.rb:5:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/tiago/.local/share/gem/ruby/3.3.0/gems/tmuxinator-3.3.3/lib/tmuxinator/util.rb:5:in `<module:Util>'
        from /home/tiago/.local/share/gem/ruby/3.3.0/gems/tmuxinator-3.3.3/lib/tmuxinator/util.rb:4:in `<module:Tmuxinator>'
        from /home/tiago/.local/share/gem/ruby/3.3.0/gems/tmuxinator-3.3.3/lib/tmuxinator/util.rb:3:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/tiago/.local/share/gem/ruby/3.3.0/gems/tmuxinator-3.3.3/lib/tmuxinator.rb:15:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/tiago/.local/share/gem/ruby/3.3.0/gems/tmuxinator-3.3.3/bin/tmuxinator:7:in `<top (required)>'
        from /usr/bin/tmuxinator:25:in `load'
        from /usr/bin/tmuxinator:25:in `<main>'
```

**Comment by SoulRamC** [comment]
Try checking if erb is available on your ruby installation using this command:
`ruby -r erb -e "puts 'ERB library is available'"`
If it didn't work, you can try to install erb using the following command:
`gem install erb`
Try the previous command to see if erb exists now. If it does, try running tmuxinator.

If nothing worked, you can attempt to reinstall ruby to make sure there are no missing libraries.

**Comment by SyscallBrain** [comment]
Thanks for the answer, I installed the erb gem now it works.

**Comment by akofink** [comment]
I thought maybe we should specify erb as a runtime dependency, but the erb gem is supposed to be installed alongside ruby 🤔

I even tried to uninstall it to reproduce this issue:

```sh
$ gem uninstall erb
Gem erb-4.0.4 cannot be uninstalled because it is a default gem
```

It's for sure part of the ruby standard library: https://stdgems.org/erb/

So it's unclear how you got into this situation - perhaps a bad ruby install, or Ruby 3.3.0 had some issue?

Regardless, glad you were able to figure out a fix.
